// <auto-generated />
namespace WebVentas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addEmpresaId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEmpresaId));
        
        string IMigrationMetadata.Id
        {
            get { return "201803222125248_addEmpresaId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
